### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by drvinceknight** [AlexPof/opycleid#1]
> Installation: Does installation proceed as outlined in the documentation?

At present I do not see installation instructions in the documentation. `pip install opycleid` works fine for me so perhaps we can add that to the README and tutorial but also include from source instructions as well?

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

After a recent review of a paper of my own it's been explained to me that `paper.md` needs a specific `# Statement of need` section. I believe this would just correspond to your last two paragraphs.

> Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

I do not believe that there are any automated tests. Perhaps your examples (README/docs) could be doctested? Or explicitly described as a way to verify that the software is working correctly?

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

These are missing (once written they can relate to the point of automated testing).

**Comment by AlexPof** [comment]
I have rewritten the ReadMe file to take account of your remarks.

- Installation instructions and dependencies are now clearly stated. As you noted, pip was the easiest way to install the package.
- The `paper.md` has been modified to include an explicit `# Statement of need section`.
- Manual tests are preferred in this case. I have rewritten and expanded the examples in the ReadMe, and explicitly stated them as tests.
- Contributing guidelines were mentionned in the HTML docs, but not in the ReadMe. This is now the case.

Please do not hesitate to tell me if you have additional commens.

**Comment by AlexPof** [comment]
Everything now seems in order, so I'm closing this issue

**Comment by abubelinha** [comment]
Hi. I just discovered the [Opycleid JOSS article](https://doi.org/10.21105/joss.00981). This paragraph puzzles me:

> Opycleid was designed to be used by both researchers and by students in music theory (see for example https://www.mathsstudents.leeds.ac.uk/fileadmin/user_upload/Current_Maths_UG_Students/2017_Dr_R_Sturman.pdf). The source code for Opycleid has been archived to Zenodo with the linked DOI: (**_TO BE COMPLETED_**)

- The linked example is not accessible because that web requires a login. @AlexPof : could you provide that pdf example here in github?
- Same question for the Zenodo DOI.

Could you provide both links in the main README?  
Thanks a lot in advance
@abubelinha

**Comment by AlexPof** [comment]
Hello,

Indeed, at the time it was submitted to JOSS the link to the pdf worked, but it is now protected. I’m afraid I don’t have a copy of it, but it didn’t have a lot of information in it anyway (it was just the outline of a course).
As for the DOI, you can search it directly on the Zenodo website (I never noticed the error in the submission process to JOSS before you mentionned it). But I would recommend to use the latest version of Opycleid at https://github.com/AlexPof/opycleid <https://github.com/AlexPof/opycleid> (or install it via pip).

Regards,

A.P.
